### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [proton2/java-leven#1]
Hello,

Is there a license on the code in this repository?

Is it public domain since it is based on nickgildea's code which has the public license? (https://github.com/nickgildea/leven/blob/master/LICENSE)

**Comment by proton2** [comment]
Hey! I don’t understand why the question is? If the code is made publicly available, why then the question arises - is this public domain or not? If it were different, I would not post this code at all. Is it strictly necessary that the license file be uploaded to this repository?

**Comment by ghost** [comment]
Without a license no one is allowed, legally, to redistribute/use your code. See this StackExchange answer: https://opensource.stackexchange.com/a/1721

**Comment by proton2** [comment]
https://github.com/proton2/java-leven/blob/master/LICENSE

is it ok now?

**Comment by ghost** [comment]
Yes, thanks for the clarification.

Closing the issue.
